name: Deploy Backend

on:
  push:
    branches:
      - main

    paths:
      - "backend/**"
      - "docker-compose.gcp.yml"

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Backend

        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}

          script: |
            cd /home/ubuntu/cryptoalgo

            git pull origin main

            docker compose \
              -f docker-compose.gcp.yml \
              --env-file .env.gcp \
              up -d --build backend
